### ISSUE TITLE
Can't get motion to run on Raspberry pi OS bookworm

### ISSUE THREAD

**Issue by micksulley** [Motion-Project/motion#1785]
### Did you read the guide?

Yes

### What is the base version number of Motion being used?

4.5.x

### What was the install method?

Installed via package tool

### What is base architecture?

ARM-32bit

### What is the distro being used?

Raspbian

### Disto version number

Debian GNU/Linux 12 (bookworm)

### Camera type(s) being used?

PI cam via libcamerify

### Describe the issue/problem and steps to reproduce

When I start motion I get the error 
`ERROR: ld.so: object '/usr/lib/aarch64-linux-gnu/libcamera/v4l2-compat.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored`
Motion then appears to run, I can open the web page, but when I open camera1 it says "UNABLE TO OPEN VIDEO DEVICE"
This was installed from the Raspi distro but I have also tried downloading and installing bookworm_motion_4.6.0-1_arm64 and bookworm_motion_4.5.1-1_arm64 with similar results.
I have attached my config files (added.txt to get them loaded)
[camera1.conf.txt](https://github.com/user-attachments/files/16201825/camera1.conf.txt)
[motion.conf.txt](https://github.com/user-attachments/files/16201826/motion.conf.txt)

[motion.log](https://github.com/user-attachments/files/16201839/motion.log)

### Motion log output at log_level 8

```shell
Log file was too big to paste here so attached.
```

**Comment by freekdk** [comment]
Op zaterdag 13 juli 2024 13:02:25 CEST schreef micksulley:
> ### Did you read the guide?
> 
> Yes
> 
> ### What is the base version number of Motion being used?
> 
> 4.5.x
> 
> ### What was the install method?
> 
> Installed via package tool
> 
> ### What is base architecture?
> 
> ARM-32bit
> 
> ### What is the distro being used?
> 
> Raspbian
> 
> ### Disto version number
> 
> Debian GNU/Linux 12 (bookworm)
> 
> ### Camera type(s) being used?
> 
> PI cam via libcamerify
> 
> ### Describe the issue/problem and steps to reproduce
> 
> When I start motion I get the error
> `ERROR: ld.so: object '/usr/lib/aarch64-linux-gnu/libcamera/v4l2-compat.so'
> from LD_PRELOAD cannot be preloaded (cannot open shared object file):
> ignored` Motion then appears to run, I can open the web page, but when I
> open camera1 it says "UNABLE TO OPEN VIDEO DEVICE" This was installed from
> the Raspi distro but I have also tried downloading and installing
> bookworm_motion_4.6.0-1_arm64 and bookworm_motion_4.5.1-1_arm64 with
> similar results. I have attached my config files (added.txt to get them
> loaded)
> [camera1.conf.txt](https://github.com/user-attachments/files/16201825/camera
> 1.conf.txt)
> [motion.conf.txt](https://github.com/user-attachments/files/16201826/motion
> .conf.txt)
> 
> [motion.log](https://github.com/user-attachments/files/16201839/motion.log)
> 
> ### Motion log output at log_level 8
> 
> ```shell
> Log file was too big to paste here so attached.
> ```

I faced the same problem and got it solved by changes in the /boot/firmware/
config.txt. When you search in the forum of the raspberry pi you will find 
what to change in that file. something with start_x and gui....

-- 
fr.gr.

Freek de Kruijf

**Comment by micksulley** [comment]
I found a hit suggesting changing /boot/firmware/config.txt to dtoverlay=vc4-kms-v3d
I have done that and rebooted and the problem still exists.
This is the screen output```
pi@pi-5:~ $ libcamerify motion
ERROR: ld.so: object '/usr/lib/aarch64-linux-gnu/libcamera/v4l2-compat.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
[0:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file /etc/motion/motion.conf
[0:motion] [NTC] [ALL] config_camera: Processing camera config file /etc/motion/camera1.conf
[0:motion] [NTC] [ALL] motion_startup: Logging to file (/home/pi/motion/motion.log)
```
This is the log file 
[motion.log](https://github.com/user-attachments/files/16202799/motion.log)
